#!/usr/bin/env zsh
dir=${0:h:h}
cd $dir

body='build/body.tex'

paper create-body text $body

# Create standalone figure list
#figure-list \
  #--collect-dir collected \
  #--captions text/figure-captions.md \
  #text/includes.yaml
