#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function
import yaml
from sys import argv

with open(argv[1]) as f:
    cfg = yaml.load(f)

print("# Figures\n")

for i,(key, spec) in enumerate(cfg.items()):
    if spec.pop('type','Figure') == 'Table':
        continue
    st = u"**Figure {0}:** ".format(i+1)
    st += spec['caption']
    print(st+'\n')
print("# References")
