#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Generates a list of figures and descriptions that can
# be piped to pandoc and/or latex
from __future__ import print_function
from sys import argv
from figurator import process_includes, load_spec
import re

spec = load_spec(argv[1], captions=argv[2])
__ = process_includes(spec, collect_dir='collected-figures', starred_floats=False)

for cfg, item in zip(spec,__):
    print(item)
