"""Added SIMS models.

Revision ID: 258ac9917a1a
Revises: 581c52e62110
Create Date: 2014-09-08 21:11:49.183854

"""

# revision identifiers, used by Alembic.
revision = '258ac9917a1a'
down_revision = '581c52e62110'

from alembic import op
import sqlalchemy as sa
from xenoliths.database.util import ChoiceType
from xenoliths.config import MINERALS


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sims_measurement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('mineral', ChoiceType(MINERALS), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sims_datum',
    sa.Column('measurement_id', sa.Integer(), nullable=False),
    sa.Column('element', sa.Integer(), nullable=False),
    sa.Column('norm_ppm', sa.Float(), nullable=True),
    sa.Column('norm_std', sa.Float(), nullable=True),
    sa.Column('raw_ppm', sa.Float(), nullable=True),
    sa.Column('raw_std', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['measurement_id'], ['sims_measurement.id'], ),
    sa.PrimaryKeyConstraint('measurement_id', 'element')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sims_datum')
    op.drop_table('sims_measurement')
    ### end Alembic commands ###
