"""empty message

Revision ID: 45000f7cf873
Revises: 3a028a18a9fb
Create Date: 2014-09-30 02:57:25.294415

"""

# revision identifiers, used by Alembic.
revision = '45000f7cf873'
down_revision = '3a028a18a9fb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('probe_datum',
    sa.Column('measurement_id', sa.Integer(), nullable=False),
    sa.Column('cation', sa.Integer(), nullable=False),
    sa.Column('oxide', sa.String(length=5), nullable=False),
    sa.Column('weight_percent', sa.Float(), nullable=True),
    sa.Column('molar_percent', sa.Float(), nullable=True),
    sa.Column('error', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['measurement_id'], ['probe_measurement.id'], ),
    sa.PrimaryKeyConstraint('measurement_id', 'cation')
    )
    op.add_column('probe_measurement', sa.Column('cr_number', sa.Float(), nullable=True))
    op.add_column('probe_measurement', sa.Column('mg_number', sa.Float(), nullable=True))
    op.add_column('probe_measurement', sa.Column('oxide_total', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('probe_measurement', 'oxide_total')
    op.drop_column('probe_measurement', 'mg_number')
    op.drop_column('probe_measurement', 'cr_number')
    op.drop_table('probe_datum')
    ### end Alembic commands ###
