"""Adds a column to discriminate whether our sample is a xenolith.

Revision ID: 53d79fe4c042
Revises: 1c26af57c200
Create Date: 2014-12-11 13:52:04.772597

"""

# revision identifiers, used by Alembic.
revision = '53d79fe4c042'
down_revision = '1c26af57c200'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('xenolith', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample', 'xenolith')
    ### end Alembic commands ###
