"""Added a column to specify that some SIMS data is bad.

Revision ID: 5627d8f80504
Revises: 3fe424f83049
Create Date: 2015-05-04 03:29:31.910439

"""

# revision identifiers, used by Alembic.
revision = '5627d8f80504'
down_revision = '3fe424f83049'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sims_datum', sa.Column('bad', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sims_datum', 'bad')
    ### end Alembic commands ###
