"""Adds probe-measurement session functionality

Revision ID: 3162884275ae
Revises: 3e9198a5c790
Create Date: 2015-04-10 23:42:11.909044

"""

# revision identifiers, used by Alembic.
revision = '3162884275ae'
down_revision = '3e9198a5c790'

from alembic import op
import sqlalchemy as sa

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('probe_session',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('date', sa.DateTime(), nullable=True),
        sa.Column('sample_id', sa.String(), nullable=True),
        sa.Column('translate_x', sa.Float(), nullable=True),
        sa.Column('translate_y', sa.Float(), nullable=True),
        sa.Column('rotate', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('probe_image', sa.Column('session_id', sa.Integer(), nullable=True))
    op.add_column('probe_measurement', sa.Column('session_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('probe_measurement', 'session_id')
    op.drop_column('probe_image', 'session_id')
    op.drop_table('probe_session')
    ### end Alembic commands ###
