"""Added a column to SIMS measurements table

Revision ID: 467d24bf1e2c
Revises: 258ac9917a1a
Create Date: 2014-09-08 22:12:45.471180

"""

# revision identifiers, used by Alembic.
revision = '467d24bf1e2c'
down_revision = '258ac9917a1a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sims_measurement', sa.Column('name', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sims_measurement', 'name')
    ### end Alembic commands ###
