font:
  size: 8
  family: [sans-serif]
  sans-serif:
    - Helvetica Neue
    - Helvetica
    - Arial
    - sans-serif
  weight: 200
mathtext:
  default: regular
axes:
  labelsize: 8
  titlesize: 12
  facecolor: white
  grid: false
  edgecolor: black
